### ISSUE TITLE
6. Arrays

### ISSUE THREAD

**Issue by ReneKrewinkel** [ArcticWyvern/educom-javascript-basis-1693295680#6]
<p>Bestudeer de module:</p>
<ul>
<li><a href="https://e-learning.educom.nu/essentials/JS/arrays">https://e-learning.educom.nu/essentials/JS/arrays</a></li>
<li>maak de opdracht</li>
</ul>

**Comment by ArcticWyvern** [comment]
oh ik zie nu dat de beschreven commit messages niet kloppen met het issue # zal vanaf hier de correcte nummers gebruiken
